# Generated by Django 3.2.5 on 2021-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_booking_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
